apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rentzone-secret
  namespace: rentzone
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:05403710xxxx:secret:rentzone-secret-gI5uHt"
        objectAlias: "app-secret"



